import type { NormalizedBowtie } from "@/lib/content/types";

// Row shapes for the tables created in supabase/migrations/*.sql. Kept
// hand-written (not generated) since the schema is small and stable.

/** Lifecycle of a question's stored TikTok slides. `rendering` and `failed`
 * are both retryable; a request that dies mid-render leaves `rendering` behind
 * so the bank can show it as incomplete rather than pretending it succeeded. */
export type SlideStatus = "none" | "queued" | "rendering" | "ready" | "failed";

export interface NclexQuestionRow {
  id: string;
  external_id: string | null;
  type: string;
  category: string | null;
  instructions: string | null;
  question: string;
  options: { label: string; text: string }[];
  correct_answers: string[];
  correct_answer_text: string | null;
  explanation: string | null;
  option_rationales: Record<string, string>;
  key_point: string | null;
  notes: string | null;
  format: string;
  bowtie: NormalizedBowtie | null;
  /** Generated by Postgres from the prompt, type, category, key point and every
   * option's text. Read-only, and never sent to the browser. */
  search_text?: string;
  /** Template the stored slides were rendered with, or null if never rendered. */
  template_id: string | null;
  slide_status: SlideStatus;
  slide_paths: string[] | null;
  slide_error: string | null;
  slide_rendered_at: string | null;
  created_at: string;
  updated_at: string;
}

export type TelegramPostStatus = "draft" | "scheduled" | "publishing" | "published" | "failed" | "cancelled";

/** What the SQL publisher function (telegram_publisher_tick) actually reads
 * off a row to build the Telegram API call — built once in TypeScript using
 * the exact same compat/message logic the preview uses, then frozen here so
 * editing the source question later never changes an already-scheduled
 * post. */
export interface TelegramPostSnapshot {
  question: string;
  pollOptions: string[];
  correctOptionIds: number[];
  /** Plain text for the poll's native lamp-icon field, already inside
   * Telegram's 200-char cap (see buildQuizExplanation). */
  quizExplanation: string | null;
  /** HTML rendering of the follow-up message, sent with parse_mode = HTML so
   * the "Why" / "Why the other options are wrong" / "NCLEX Key Point" headers
   * actually render as headers. Null when there's nothing extra to say. */
  followUpHtml: string | null;
  /** The same follow-up as plain text — the legacy field, kept so snapshots
   * written before followUpHtml existed still have a readable body. */
  followUpText: string | null;
  /** True when the poll must accept more than one answer. Driven by the
   * actual number of correct options rather than the declared question type,
   * so a "select all that apply" that happens to have one right answer is
   * still sent as a normal single-answer quiz. */
  isMultiple: boolean;
}

export interface TelegramScheduledPostRow {
  id: string;
  content_id: string;
  content_snapshot: TelegramPostSnapshot;
  telegram_channel: string;
  scheduled_at: string; // ISO UTC
  timezone: string;
  status: TelegramPostStatus;
  telegram_message_id: number | null;
  telegram_poll_id: string | null;
  telegram_followup_message_id: number | null;
  published_at: string | null;
  error_message: string | null;
  attempt_count: number;
  created_at: string;
  updated_at: string;
}
